server:
  port: 5000


model:
  path: 'D:/Code/Python/final-project-deep-learning/tf_model/tf_model_052024_EfficientNetB06.keras'
  drive_path: 'https://drive.google.com/uc?id=1KGYhAPySC-OXz-Sjt-JMMpdugwqw_3b2'
  class_names: ['balo_vali','bicycle','car','digital_camera','food',
              'digital_devices','fashion','glasses','home_appliances',
              'jewelry','laptop_computer','motorbike','phone_tablet','shoes_sandal']
